### ISSUE TITLE
Write complete README

### ISSUE THREAD

**Issue by cowboyd** [microstates/ember#15]
When somebody comes to the github repo they need to be able to answer the question why is this useful to me? I would I include it in my application. Then, once they make that determination, they need an effective guide to using it.

That's why the README should address these points.
- [x] Why this is important?
- [ ] Templating APIs are stable
- [x] Custom Microstates are a work in progress.
- [x]  this is not `logic in templates`?
- [x] How is this different from `ember-composable-helpers`?
- [x] Details on each type
- [ ] Callback API, details on `valueOf()` #47

**Comment by rauhryan** [comment]
Hey cowboyd!

I've finally gotten sometime to rewrite some things and I love the idea of microstates and I've been using them in some new components. 

Today I was putting together some integration tests and got some errors. 

```
Compile Error: Boolean is not a helper
```

So I tried to google around and couldn't find anything, didn't see anything on the readme so I dug into your unit tests in the repo and added 

```
import Microstates from 'ember-microstates/initializers/microstates';

/* setup code */

beforeEach(function() {
    Microstates.initialize(this.container.registry);
})

```

This got my tests happy and passing. 

Is this some special magic to get the add-on to work in integration tests?

I little blurb on the Readme would be help steer people in the right direction. 

I'm happy to contribute if you could provide me with some guidance on this.

**Comment by cowboyd** [comment]
Hey! So glad to hear that you're enjoying them. It's hard for me to look at code that doesn't use microstates anymore :)

Yeah, the problem with the integration tests is that you're running a stripped down version of the container, and initializers don't run so it has to manually add all of the microstate helpers to the application container.

I don't know what the right thing to do here is. Either put something in the README, or perhaps make it automagical in some way. Like automatically updating the testing helper.

**Comment by taras** [comment]
Such change, very update. WOW
