### ISSUE TITLE
Support cap on number of choices for multiple `Select`

### ISSUE THREAD

**Issue by cowboyd** [microstates/ember#42]
The current `Select` microstate either allows you to either be `multiple` or `single`. In the case of multiple, the number of potential selections is `N` where `N` is the length of the number of options. In the case of a single select, then number of potential selections is `1`.  But what if there is an in-between ground. In other words, what if I have a set of 10 colors, but I need to choose 3? Seems like we should support a `max` option on the multiple choice variety which begins deselecting choices after the max has been attained.

``` hbs
{{let animals=(Select (array 'cat' 'dog' 'bird' 'fish') multiple=true max=2)}}

Choose your {{animals.max}} favorite animals:

{{#each animals as |animal|}}
  <label> {{animal.value}} <input type="checkbox" onclick={{action animal.toggle}} selected={{animal.isSelected}}/></label>
{{/each}}
```

Open questions: 
- should `max=N` _imply_ `multiple`?
- should it fire `on-deselect` whenever an option is deselected automatically?

**Comment by taras** [comment]
This API no longer exists.
