### ISSUE TITLE
Document callback API, and why you might need to use `valueOf()`

### ISSUE THREAD

**Issue by cowboyd** [microstates/ember#47]
Every helper has a callback API that you can use to bind actions to the various state transitions. 

``` hbs
{{let isOn=(Boolean false on-toggle=(action "logToggle"))}}

is On? <input type=checkbox checked={{isOn}}/><br/>

<button onclick={{action isOn.toggle}}>Light Switch</button>
```

We need to let library users know about the existence of this api, and when you might want to consider using it.

It should re-enforce the general microstate form `(Microstate value options)` and enumerate the three built-in events, `on-init`, `on-state`, and `on-[transitionName]`

Finally, because the actual value is wrapped so that it can behave nicely with the handlebars, you may need to "unbox" the state to get at the actual value it represents. This is less important for object based states, but critical for primitive microstates like booleans and numbers since the boxed value will act radically different from the unboxed value.

Examples such as the gotchas present with a boolean should be given.

**Comment by taras** [comment]
Not necessary anymore. We can return to this if it becomes necessary in the future.
