### ISSUE TITLE
String microstate instance is not strictly equal to it's primitive value

### ISSUE THREAD

**Issue by taras** [microstates/ember#61]
The Microstate object is loosely equal to it's original value but not strictly equal.  You can reproduce this through experimentation:
- `Object.create(new String("hello world")) === "hello world" //=> false`
- `new String("hello world") === "hello world" //=> false`
- `new String("hello world") == "hello world" //=> true`

The problem with `ember-composable-helpers` compatibility of `filter-by` helper, that was reported by me in #60, is rooted in `filter-by` helper doing strict equality comparison when checking item equality. `filter-by` is doing the right thing.

This also applies to Boolean and Number states.

**Comment by cowboyd** [comment]
This is an attribute of JavaScript that we just can't get around:

```js
new String('hello') === new String('hello') //=> false
new String('hello').valueOf() === new String('hello').valueOf() //=> true
```

We can either request that they explicitly do a `valueOf()` unwrap before doing a comparison, or alternatively, use `Ember.isEqual` for and then we implement the `equals` method on the `String` instance.

**Comment by taras** [comment]
It might be easier for us to focus on Microstates as being a template primitive and not leak them into the JavaScript environment. There are several borders between the template and JavaScript that we can consider separately.

## Helper#compute
One solution could be to provide a compatibility wrapper for `compute` function that'll unbox the parameters that are passed into compute. 

```hbs
import microstateCompatible from 'ember-microstates/compatibility';

export default Ember.Helper.helper(microstateCompatible(function(params, options){
  // all microstates in params and options will be converted to primitive values
}));

export default Ember.Helper.extend({
  compute: microstateCompatible(function(params, options) {
    // all microstates in params and options will be converted to primitive values
  })
});
```

## Actions
I'm not sure how to handle actions that bubble up to the component or the controller. We could provide a helper `{{action 'componentAction' (value-of isOpen)}}`. This seems very verbose. It'd be great if it was handled Glimmer level so users don't need to do anything special.

Another thing that I've been thinking - we might need a way to identify a microstate. What do you think about adding a `isMicrostate=true` property that we can use to say: `if (obj.isMicrostate) obj.valueOf()`?

**Comment by cowboyd** [comment]
> One solution could be to provide a compatibility wrapper for compute function that'll unbox the parameters that are passed into compute. 

If we make it opt-in, then we're signing up for a world of hurt. By including microstates in your application, you're already opting in to microstates, so it's going to be really annoying if it's a constant fight to make the addons you use compatible. 

You've identified the two cases where this is a problem: derived state via `Helper#compute` and message passing via `{{action}}`. In the first case, unboxing is what's called for because the actions are not needed in derived state. Actions are for initiating state transitions, i.e. side-effects and so don't really have any place in a `compute` which should model a pure function.

In the case of actions though, we _do_ want the decorated microstate passed to the action handler. This is key to the functionality of the `on-init=(action "startUploadImmediately")` which begins a file upload as soon as it is allocated.

```js
actions: {
  startUploadImmediately(upload) {
    upload.start();
  }
}
```

So what if we reopened `Helper` to compute with the unboxed value?

**Comment by taras** [comment]
> By including microstates in your application, you're already opting in to microstates, so it's going to be really annoying if it's a constant fight to make the addons you use compatible.

I agree. This not ideal.

> So what if we reopened Helper to compute with the unboxed value?

There are a few considerations that make me doubt this options.

We can reopen `Helper` class but this will only affect Helper Factories(which ember-composable-helpers are, btw). The problem is that people don't call `this._super` in the `compute` method. It's not clear how we'd make our compute code invocable. 

For helper instances, we have nothing to overload.

Another solution could be to customize the helpers that are in the registry. We could iterate these and possibly modify their factories. This might get really messed up with modules, but we could deal with this later(possibly).

**Comment by cowboyd** [comment]
> We can reopen Helper class but this will only affect Helper Factories(which ember-composable-helpers are, btw). The problem is that people don't call this._super in the compute method. It's not clear how we'd make our compute code invocable.

I think what we'd be actually doing is changing reopening the `HelperFactoryStream` and its equivalent in glimmer.

**Comment by taras** [comment]
Microstates now have `state` property that can be used to compare equality to primitive values.
