### ISSUE TITLE
Aligning this with latest microstate.js

### ISSUE THREAD

**Issue by knownasilya** [microstates/ember#68]
I'd love to get this to work with that library. What would that look like?

---

Current implementation happening here: https://github.com/cowboyd/ember-microstates/pull/69

**Comment by taras** [comment]
Yes, this would be in place of the helper(helpers would need to be removed).

**Comment by knownasilya** [comment]
I'll submit a PR for the first use case, at least to get something going.

**Comment by taras** [comment]
Let me know if you’d like help.

**Comment by knownasilya** [comment]
Started work here https://github.com/knownasilya/ember-microstates/blob/update/addon/components/state-for.js

**Comment by taras** [comment]
Resolved by #72
